server:
  port: 9090

keycloak:
  realm: springboot-integration
  resource: springboot-security
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  confidential-port: 0
  public-client: true
  principal-attribute: preferred_username


logging:
  level:
    org:
      springframework:
        security:  DEBUG


spring:
  security:
    ignore:
      urls:
        - /
        - /sso/logout
        - /cat
        - /dog
        - /css/**
        - images/**

